const level1 = new Level(
  [
    new Chicken(0),
    new Chicken(0),
    new Chicken(1),
    new Chicken(1),
    new Chicken(2),
    new Chicken(2),
    new Chicken(2),
    new Chicken(3),
    new Chicken(3),
    new Chicken(4),
    new Chicken(4),
    new Chicken(5),
    new Chicken(5),
    new SmallChicken(0),
    new SmallChicken(0),
    new SmallChicken(1),
    new SmallChicken(1),
    new SmallChicken(2),
    new SmallChicken(2),
    new SmallChicken(3),
    new SmallChicken(3),
    new SmallChicken(4),
    new SmallChicken(4),
    new SmallChicken(5),
    new SmallChicken(5),
    new Endboss(),
  ],
  [
    new Cloud(0),
    new Cloud(1),
    new Cloud(2),
    new Cloud(3),
    new Cloud(4),
    new Cloud(5),
    new Cloud(6),
    new Cloud(7),
  ],
  [
    new Bottle(0),
    new Bottle(0),
    new Bottle(0),
    new Bottle(1),
    new Bottle(1),
    new Bottle(1),
    new Bottle(2),
    new Bottle(2),
    new Bottle(3),
    new Bottle(3),
    new Bottle(4),
    new Bottle(4),
    new Bottle(5),
    new Bottle(5),
  ],
  [
    new Coin(0),
    new Coin(0),
    new Coin(0),
    new Coin(1),
    new Coin(1),
    new Coin(1),
    new Coin(1),
    new Coin(1),
    new Coin(2),
    new Coin(2),
    new Coin(2),
    new Coin(3),
    new Coin(3),
    new Coin(3),
    new Coin(4),
    new Coin(4),
    new Coin(4),
    new Coin(5),
    new Coin(5),
    new Coin(5),
  ],

  numberBackgroundLayers
);
